name: Build_debug

on:
  push:
    tags:
       - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Clean build directory
        run: | 
          if (Test-Path build) { Remove-Item -Recurse -Force build }
        
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1

      - uses: jurplel/install-qt-action@v3
        with:
          version: 6.9.2
          arch: win64_msvc2022_64
          cache: true

      - name: Bootstrap dependencies
        shell: cmd
        run: call libs/clone_dependencies.bat
        working-directory: ${{ github.workspace }}


      - name: Configure
        run: >
          cmake -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build
        run: cmake --build build --config Debug

      - uses: actions/upload-artifact@v4
        with:
          name: BlainnflareEngine-${{ github.ref_name }}
          path: build/**
